export interface CountryOption {
  name: string;
  flag: string;
  region: string;
}

export const countries: CountryOption[] = [
  { name: "Afghanistan", flag: "🇦🇫", region: "Asia" },
  { name: "Albania", flag: "🇦🇱", region: "Europe" },
  { name: "Algeria", flag: "🇩🇿", region: "Africa" },
  { name: "Andorra", flag: "🇦🇩", region: "Europe" },
  { name: "Angola", flag: "🇦🇴", region: "Africa" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", region: "Americas" },
  { name: "Argentina", flag: "🇦🇷", region: "Americas" },
  { name: "Armenia", flag: "🇦🇲", region: "Asia" },
  { name: "Australia", flag: "🇦🇺", region: "Oceania" },
  { name: "Austria", flag: "🇦🇹", region: "Europe" },
  { name: "Azerbaijan", flag: "🇦🇿", region: "Asia" },
  { name: "Bahamas", flag: "🇧🇸", region: "Americas" },
  { name: "Bahrain", flag: "🇧🇭", region: "Asia" },
  { name: "Bangladesh", flag: "🇧🇩", region: "Asia" },
  { name: "Barbados", flag: "🇧🇧", region: "Americas" },
  { name: "Belarus", flag: "🇧🇾", region: "Europe" },
  { name: "Belgium", flag: "🇧🇪", region: "Europe" },
  { name: "Belize", flag: "🇧🇿", region: "Americas" },
  { name: "Benin", flag: "🇧🇯", region: "Africa" },
  { name: "Bhutan", flag: "🇧🇹", region: "Asia" },
  { name: "Bolivia", flag: "🇧🇴", region: "Americas" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", region: "Europe" },
  { name: "Botswana", flag: "🇧🇼", region: "Africa" },
  { name: "Brazil", flag: "🇧🇷", region: "Americas" },
  { name: "Brunei", flag: "🇧🇳", region: "Asia" },
  { name: "Bulgaria", flag: "🇧🇬", region: "Europe" },
  { name: "Burkina Faso", flag: "🇧🇫", region: "Africa" },
  { name: "Burundi", flag: "🇧🇮", region: "Africa" },
  { name: "Cambodia", flag: "🇰🇭", region: "Asia" },
  { name: "Cameroon", flag: "🇨🇲", region: "Africa" },
  { name: "Canada", flag: "🇨🇦", region: "Americas" },
  { name: "Cape Verde", flag: "🇨🇻", region: "Africa" },
  { name: "Central African Republic", flag: "🇨🇫", region: "Africa" },
  { name: "Chad", flag: "🇹🇩", region: "Africa" },
  { name: "Chile", flag: "🇨🇱", region: "Americas" },
  { name: "China", flag: "🇨🇳", region: "Asia" },
  { name: "Colombia", flag: "🇨🇴", region: "Americas" },
  { name: "Comoros", flag: "🇰🇲", region: "Africa" },
  { name: "Congo", flag: "🇨🇬", region: "Africa" },
  { name: "Costa Rica", flag: "🇨🇷", region: "Americas" },
  { name: "Croatia", flag: "🇭🇷", region: "Europe" },
  { name: "Cuba", flag: "🇨🇺", region: "Americas" },
  { name: "Cyprus", flag: "🇨🇾", region: "Europe" },
  { name: "Czech Republic", flag: "🇨🇿", region: "Europe" },
  { name: "Denmark", flag: "🇩🇰", region: "Europe" },
  { name: "Djibouti", flag: "🇩🇯", region: "Africa" },
  { name: "Dominica", flag: "🇩🇲", region: "Americas" },
  { name: "Dominican Republic", flag: "🇩🇴", region: "Americas" },
  { name: "Ecuador", flag: "🇪🇨", region: "Americas" },
  { name: "Egypt", flag: "🇪🇬", region: "Africa" },
  { name: "El Salvador", flag: "🇸🇻", region: "Americas" },
  { name: "Equatorial Guinea", flag: "🇬🇶", region: "Africa" },
  { name: "Eritrea", flag: "🇪🇷", region: "Africa" },
  { name: "Estonia", flag: "🇪🇪", region: "Europe" },
  { name: "Eswatini", flag: "🇸🇿", region: "Africa" },
  { name: "Ethiopia", flag: "🇪🇹", region: "Africa" },
  { name: "Fiji", flag: "🇫🇯", region: "Oceania" },
  { name: "Finland", flag: "🇫🇮", region: "Europe" },
  { name: "France", flag: "🇫🇷", region: "Europe" },
  { name: "Gabon", flag: "🇬🇦", region: "Africa" },
  { name: "Gambia", flag: "🇬🇲", region: "Africa" },
  { name: "Georgia", flag: "🇬🇪", region: "Asia" },
  { name: "Germany", flag: "🇩🇪", region: "Europe" },
  { name: "Ghana", flag: "🇬🇭", region: "Africa" },
  { name: "Greece", flag: "🇬🇷", region: "Europe" },
  { name: "Grenada", flag: "🇬🇩", region: "Americas" },
  { name: "Guatemala", flag: "🇬🇹", region: "Americas" },
  { name: "Guinea", flag: "🇬🇳", region: "Africa" },
  { name: "Guinea-Bissau", flag: "🇬🇼", region: "Africa" },
  { name: "Guyana", flag: "🇬🇾", region: "Americas" },
  { name: "Haiti", flag: "🇭🇹", region: "Americas" },
  { name: "Honduras", flag: "🇭🇳", region: "Americas" },
  { name: "Hungary", flag: "🇭🇺", region: "Europe" },
  { name: "Iceland", flag: "🇮🇸", region: "Europe" },
  { name: "India", flag: "🇮🇳", region: "Asia" },
  { name: "Indonesia", flag: "🇮🇩", region: "Asia" },
  { name: "Iran", flag: "🇮🇷", region: "Asia" },
  { name: "Iraq", flag: "🇮🇶", region: "Asia" },
  { name: "Ireland", flag: "🇮🇪", region: "Europe" },
  { name: "Israel", flag: "🇮🇱", region: "Asia" },
  { name: "Italy", flag: "🇮🇹", region: "Europe" },
  { name: "Jamaica", flag: "🇯🇲", region: "Americas" },
  { name: "Japan", flag: "🇯🇵", region: "Asia" },
  { name: "Jordan", flag: "🇯🇴", region: "Asia" },
  { name: "Kazakhstan", flag: "🇰🇿", region: "Asia" },
  { name: "Kenya", flag: "🇰🇪", region: "Africa" },
  { name: "Kiribati", flag: "🇰🇮", region: "Oceania" },
  { name: "Kosovo", flag: "🇽🇰", region: "Europe" },
  { name: "Kuwait", flag: "🇰🇼", region: "Asia" },
  { name: "Kyrgyzstan", flag: "🇰🇬", region: "Asia" },
  { name: "Laos", flag: "🇱🇦", region: "Asia" },
  { name: "Latvia", flag: "🇱🇻", region: "Europe" },
  { name: "Lebanon", flag: "🇱🇧", region: "Asia" },
  { name: "Lesotho", flag: "🇱🇸", region: "Africa" },
  { name: "Liberia", flag: "🇱🇷", region: "Africa" },
  { name: "Libya", flag: "🇱🇾", region: "Africa" },
  { name: "Liechtenstein", flag: "🇱🇮", region: "Europe" },
  { name: "Lithuania", flag: "🇱🇹", region: "Europe" },
  { name: "Luxembourg", flag: "🇱🇺", region: "Europe" },
  { name: "Madagascar", flag: "🇲🇬", region: "Africa" },
  { name: "Malawi", flag: "🇲🇼", region: "Africa" },
  { name: "Malaysia", flag: "🇲🇾", region: "Asia" },
  { name: "Maldives", flag: "🇲🇻", region: "Asia" },
  { name: "Mali", flag: "🇲🇱", region: "Africa" },
  { name: "Malta", flag: "🇲🇹", region: "Europe" },
  { name: "Marshall Islands", flag: "🇲🇭", region: "Oceania" },
  { name: "Mauritania", flag: "🇲🇷", region: "Africa" },
  { name: "Mauritius", flag: "🇲🇺", region: "Africa" },
  { name: "Mexico", flag: "🇲🇽", region: "Americas" },
  { name: "Micronesia", flag: "🇫🇲", region: "Oceania" },
  { name: "Moldova", flag: "🇲🇩", region: "Europe" },
  { name: "Monaco", flag: "🇲🇨", region: "Europe" },
  { name: "Mongolia", flag: "🇲🇳", region: "Asia" },
  { name: "Montenegro", flag: "🇲🇪", region: "Europe" },
  { name: "Morocco", flag: "🇲🇦", region: "Africa" },
  { name: "Mozambique", flag: "🇲🇿", region: "Africa" },
  { name: "Myanmar", flag: "🇲🇲", region: "Asia" },
  { name: "Namibia", flag: "🇳🇦", region: "Africa" },
  { name: "Nauru", flag: "🇳🇷", region: "Oceania" },
  { name: "Nepal", flag: "🇳🇵", region: "Asia" },
  { name: "Netherlands", flag: "🇳🇱", region: "Europe" },
  { name: "New Zealand", flag: "🇳🇿", region: "Oceania" },
  { name: "Nicaragua", flag: "🇳🇮", region: "Americas" },
  { name: "Niger", flag: "🇳🇪", region: "Africa" },
  { name: "Nigeria", flag: "🇳🇬", region: "Africa" },
  { name: "North Korea", flag: "🇰🇵", region: "Asia" },
  { name: "North Macedonia", flag: "🇲🇰", region: "Europe" },
  { name: "Norway", flag: "🇳🇴", region: "Europe" },
  { name: "Oman", flag: "🇴🇲", region: "Asia" },
  { name: "Pakistan", flag: "🇵🇰", region: "Asia" },
  { name: "Palau", flag: "🇵🇼", region: "Oceania" },
  { name: "Palestine", flag: "🇵🇸", region: "Asia" },
  { name: "Panama", flag: "🇵🇦", region: "Americas" },
  { name: "Papua New Guinea", flag: "🇵🇬", region: "Oceania" },
  { name: "Paraguay", flag: "🇵🇾", region: "Americas" },
  { name: "Peru", flag: "🇵🇪", region: "Americas" },
  { name: "Philippines", flag: "🇵🇭", region: "Asia" },
  { name: "Poland", flag: "🇵🇱", region: "Europe" },
  { name: "Portugal", flag: "🇵🇹", region: "Europe" },
  { name: "Qatar", flag: "🇶🇦", region: "Asia" },
  { name: "Romania", flag: "🇷🇴", region: "Europe" },
  { name: "Russia", flag: "🇷🇺", region: "Europe" },
  { name: "Rwanda", flag: "🇷🇼", region: "Africa" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", region: "Americas" },
  { name: "Saint Lucia", flag: "🇱🇨", region: "Americas" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", region: "Americas" },
  { name: "Samoa", flag: "🇼🇸", region: "Oceania" },
  { name: "San Marino", flag: "🇸🇲", region: "Europe" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", region: "Africa" },
  { name: "Saudi Arabia", flag: "🇸🇦", region: "Asia" },
  { name: "Senegal", flag: "🇸🇳", region: "Africa" },
  { name: "Serbia", flag: "🇷🇸", region: "Europe" },
  { name: "Seychelles", flag: "🇸🇨", region: "Africa" },
  { name: "Sierra Leone", flag: "🇸🇱", region: "Africa" },
  { name: "Singapore", flag: "🇸🇬", region: "Asia" },
  { name: "Slovakia", flag: "🇸🇰", region: "Europe" },
  { name: "Slovenia", flag: "🇸🇮", region: "Europe" },
  { name: "Solomon Islands", flag: "🇸🇧", region: "Oceania" },
  { name: "Somalia", flag: "🇸🇴", region: "Africa" },
  { name: "South Africa", flag: "🇿🇦", region: "Africa" },
  { name: "South Korea", flag: "🇰🇷", region: "Asia" },
  { name: "South Sudan", flag: "🇸🇸", region: "Africa" },
  { name: "Spain", flag: "🇪🇸", region: "Europe" },
  { name: "Sri Lanka", flag: "🇱🇰", region: "Asia" },
  { name: "Sudan", flag: "🇸🇩", region: "Africa" },
  { name: "Suriname", flag: "🇸🇷", region: "Americas" },
  { name: "Sweden", flag: "🇸🇪", region: "Europe" },
  { name: "Switzerland", flag: "🇨🇭", region: "Europe" },
  { name: "Syria", flag: "🇸🇾", region: "Asia" },
  { name: "Taiwan", flag: "🇹🇼", region: "Asia" },
  { name: "Tajikistan", flag: "🇹🇯", region: "Asia" },
  { name: "Tanzania", flag: "🇹🇿", region: "Africa" },
  { name: "Thailand", flag: "🇹🇭", region: "Asia" },
  { name: "Timor-Leste", flag: "🇹🇱", region: "Asia" },
  { name: "Togo", flag: "🇹🇬", region: "Africa" },
  { name: "Tonga", flag: "🇹🇴", region: "Oceania" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", region: "Americas" },
  { name: "Tunisia", flag: "🇹🇳", region: "Africa" },
  { name: "Turkey", flag: "🇹🇷", region: "Asia" },
  { name: "Turkmenistan", flag: "🇹🇲", region: "Asia" },
  { name: "Tuvalu", flag: "🇹🇻", region: "Oceania" },
  { name: "Uganda", flag: "🇺🇬", region: "Africa" },
  { name: "Ukraine", flag: "🇺🇦", region: "Europe" },
  { name: "United Arab Emirates", flag: "🇦🇪", region: "Asia" },
  { name: "United Kingdom", flag: "🇬🇧", region: "Europe" },
  { name: "United States", flag: "🇺🇸", region: "Americas" },
  { name: "Uruguay", flag: "🇺🇾", region: "Americas" },
  { name: "Uzbekistan", flag: "🇺🇿", region: "Asia" },
  { name: "Vanuatu", flag: "🇻🇺", region: "Oceania" },
  { name: "Vatican City", flag: "🇻🇦", region: "Europe" },
  { name: "Venezuela", flag: "🇻🇪", region: "Americas" },
  { name: "Vietnam", flag: "🇻🇳", region: "Asia" },
  { name: "Yemen", flag: "🇾🇪", region: "Asia" },
  { name: "Zambia", flag: "🇿🇲", region: "Africa" },
  { name: "Zimbabwe", flag: "🇿🇼", region: "Africa" },
];

export function searchCountries(query: string): CountryOption[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return countries
    .filter((c) => c.name.toLowerCase().startsWith(q))
    .slice(0, 7);
}
