type PowerInfo = {
  plugTypes: string[];
  voltage: string;
  frequency: string;
};

const powerData: Record<string, PowerInfo> = {
  AF: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  AL: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  DZ: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  AD: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  AO: { plugTypes: ["C"], voltage: "220V", frequency: "50Hz" },
  AG: { plugTypes: ["A", "B"], voltage: "230V", frequency: "60Hz" },
  AR: { plugTypes: ["C", "I"], voltage: "220V", frequency: "50Hz" },
  AM: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  AU: { plugTypes: ["I"], voltage: "230V", frequency: "50Hz" },
  AT: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  AZ: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  BS: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  BH: { plugTypes: ["G"], voltage: "230V", frequency: "50Hz" },
  BD: { plugTypes: ["C", "D", "G", "K"], voltage: "220V", frequency: "50Hz" },
  BB: { plugTypes: ["A", "B"], voltage: "115V", frequency: "50Hz" },
  BY: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  BE: { plugTypes: ["C", "E"], voltage: "230V", frequency: "50Hz" },
  BZ: { plugTypes: ["A", "B", "G"], voltage: "110V/220V", frequency: "60Hz" },
  BJ: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  BT: { plugTypes: ["D", "F", "G"], voltage: "230V", frequency: "50Hz" },
  BO: { plugTypes: ["A", "C"], voltage: "230V", frequency: "50Hz" },
  BA: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  BW: { plugTypes: ["D", "G"], voltage: "230V", frequency: "50Hz" },
  BR: { plugTypes: ["C", "N"], voltage: "127V/220V", frequency: "60Hz" },
  BN: { plugTypes: ["G"], voltage: "240V", frequency: "50Hz" },
  BG: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  BF: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  BI: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  KH: { plugTypes: ["A", "C", "G"], voltage: "230V", frequency: "50Hz" },
  CM: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  CA: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  CV: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  CF: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  TD: { plugTypes: ["C", "D", "E", "F"], voltage: "220V", frequency: "50Hz" },
  CL: { plugTypes: ["C", "L"], voltage: "220V", frequency: "50Hz" },
  CN: { plugTypes: ["A", "C", "I"], voltage: "220V", frequency: "50Hz" },
  CO: { plugTypes: ["A", "B"], voltage: "110V", frequency: "60Hz" },
  KM: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  CD: { plugTypes: ["C", "D", "E"], voltage: "220V", frequency: "50Hz" },
  CG: { plugTypes: ["C", "E"], voltage: "230V", frequency: "50Hz" },
  CR: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  HR: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  CU: { plugTypes: ["A", "B", "C", "L"], voltage: "110V/220V", frequency: "60Hz" },
  CY: { plugTypes: ["G"], voltage: "240V", frequency: "50Hz" },
  CZ: { plugTypes: ["C", "E"], voltage: "230V", frequency: "50Hz" },
  DK: { plugTypes: ["C", "E", "F", "K"], voltage: "230V", frequency: "50Hz" },
  DJ: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  DM: { plugTypes: ["D", "G"], voltage: "230V", frequency: "50Hz" },
  DO: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  EC: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  EG: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  SV: { plugTypes: ["A", "B"], voltage: "115V", frequency: "60Hz" },
  GQ: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  ER: { plugTypes: ["C", "L"], voltage: "230V", frequency: "50Hz" },
  EE: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  SZ: { plugTypes: ["M"], voltage: "230V", frequency: "50Hz" },
  ET: { plugTypes: ["C", "E", "F", "L"], voltage: "220V", frequency: "50Hz" },
  FJ: { plugTypes: ["I"], voltage: "240V", frequency: "50Hz" },
  FI: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  FR: { plugTypes: ["C", "E"], voltage: "230V", frequency: "50Hz" },
  GA: { plugTypes: ["C"], voltage: "220V", frequency: "50Hz" },
  GM: { plugTypes: ["G"], voltage: "230V", frequency: "50Hz" },
  GE: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  DE: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  GH: { plugTypes: ["D", "G"], voltage: "230V", frequency: "50Hz" },
  GR: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  GD: { plugTypes: ["G"], voltage: "230V", frequency: "50Hz" },
  GT: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  GN: { plugTypes: ["C", "F", "K"], voltage: "220V", frequency: "50Hz" },
  GW: { plugTypes: ["C"], voltage: "220V", frequency: "50Hz" },
  GY: { plugTypes: ["A", "B", "D", "G"], voltage: "240V", frequency: "60Hz" },
  HT: { plugTypes: ["A", "B"], voltage: "110V", frequency: "60Hz" },
  HN: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  HU: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  IS: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  IN: { plugTypes: ["C", "D", "M"], voltage: "230V", frequency: "50Hz" },
  ID: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  IR: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  IQ: { plugTypes: ["C", "D", "G"], voltage: "230V", frequency: "50Hz" },
  IE: { plugTypes: ["G"], voltage: "230V", frequency: "50Hz" },
  IL: { plugTypes: ["C", "H"], voltage: "230V", frequency: "50Hz" },
  IT: { plugTypes: ["C", "F", "L"], voltage: "230V", frequency: "50Hz" },
  CI: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  JM: { plugTypes: ["A", "B"], voltage: "110V", frequency: "50Hz" },
  JP: { plugTypes: ["A", "B"], voltage: "100V", frequency: "50/60Hz" },
  JO: { plugTypes: ["B", "C", "D", "F", "G", "J"], voltage: "230V", frequency: "50Hz" },
  KZ: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  KE: { plugTypes: ["G"], voltage: "240V", frequency: "50Hz" },
  KI: { plugTypes: ["I"], voltage: "240V", frequency: "50Hz" },
  KP: { plugTypes: ["A", "C", "F"], voltage: "220V", frequency: "50Hz" },
  KR: { plugTypes: ["C", "F"], voltage: "220V", frequency: "60Hz" },
  KW: { plugTypes: ["C", "G"], voltage: "240V", frequency: "50Hz" },
  KG: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  LA: { plugTypes: ["A", "B", "C", "E", "F"], voltage: "230V", frequency: "50Hz" },
  LV: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  LB: { plugTypes: ["C", "D", "G"], voltage: "230V", frequency: "50Hz" },
  LS: { plugTypes: ["M"], voltage: "220V", frequency: "50Hz" },
  LR: { plugTypes: ["A", "B", "C", "E", "F"], voltage: "120V/240V", frequency: "60Hz" },
  LY: { plugTypes: ["C", "D", "F", "L"], voltage: "127V/230V", frequency: "50Hz" },
  LI: { plugTypes: ["C", "J"], voltage: "230V", frequency: "50Hz" },
  LT: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  LU: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  MG: { plugTypes: ["C", "D", "E", "J", "K"], voltage: "220V", frequency: "50Hz" },
  MW: { plugTypes: ["G"], voltage: "230V", frequency: "50Hz" },
  MY: { plugTypes: ["G"], voltage: "240V", frequency: "50Hz" },
  MV: { plugTypes: ["A", "D", "G", "J", "K", "L"], voltage: "230V", frequency: "50Hz" },
  ML: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  MT: { plugTypes: ["G"], voltage: "230V", frequency: "50Hz" },
  MH: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  MR: { plugTypes: ["C"], voltage: "220V", frequency: "50Hz" },
  MU: { plugTypes: ["C", "G"], voltage: "230V", frequency: "50Hz" },
  MX: { plugTypes: ["A", "B"], voltage: "127V", frequency: "60Hz" },
  FM: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  MD: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  MC: { plugTypes: ["C", "D", "E", "F"], voltage: "230V", frequency: "50Hz" },
  MN: { plugTypes: ["C", "E"], voltage: "230V", frequency: "50Hz" },
  ME: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  MA: { plugTypes: ["C", "E"], voltage: "220V", frequency: "50Hz" },
  MZ: { plugTypes: ["C", "F", "M"], voltage: "220V", frequency: "50Hz" },
  MM: { plugTypes: ["C", "D", "F", "G"], voltage: "230V", frequency: "50Hz" },
  NA: { plugTypes: ["D", "M"], voltage: "220V", frequency: "50Hz" },
  NR: { plugTypes: ["I"], voltage: "240V", frequency: "50Hz" },
  NP: { plugTypes: ["C", "D", "M"], voltage: "230V", frequency: "50Hz" },
  NL: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  NZ: { plugTypes: ["I"], voltage: "230V", frequency: "50Hz" },
  NI: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  NE: { plugTypes: ["A", "B", "C", "D", "E", "F"], voltage: "220V", frequency: "50Hz" },
  NG: { plugTypes: ["D", "G"], voltage: "240V", frequency: "50Hz" },
  MK: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  NO: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  OM: { plugTypes: ["C", "G"], voltage: "240V", frequency: "50Hz" },
  PK: { plugTypes: ["C", "D"], voltage: "230V", frequency: "50Hz" },
  PW: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  PA: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  PG: { plugTypes: ["I"], voltage: "240V", frequency: "50Hz" },
  PY: { plugTypes: ["C"], voltage: "220V", frequency: "50Hz" },
  PE: { plugTypes: ["A", "B", "C"], voltage: "220V", frequency: "60Hz" },
  PH: { plugTypes: ["A", "B", "C"], voltage: "220V", frequency: "60Hz" },
  PL: { plugTypes: ["C", "E"], voltage: "230V", frequency: "50Hz" },
  PT: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  QA: { plugTypes: ["D", "G"], voltage: "240V", frequency: "50Hz" },
  RO: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  RU: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  RW: { plugTypes: ["C", "J"], voltage: "230V", frequency: "50Hz" },
  KN: { plugTypes: ["A", "B", "D", "G"], voltage: "230V", frequency: "60Hz" },
  LC: { plugTypes: ["G"], voltage: "240V", frequency: "50Hz" },
  VC: { plugTypes: ["A", "C", "E", "G", "I", "K"], voltage: "230V", frequency: "50Hz" },
  WS: { plugTypes: ["I"], voltage: "230V", frequency: "50Hz" },
  SM: { plugTypes: ["C", "F", "L"], voltage: "230V", frequency: "50Hz" },
  ST: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  SA: { plugTypes: ["A", "B", "G"], voltage: "220V", frequency: "60Hz" },
  SN: { plugTypes: ["C", "D", "E", "K"], voltage: "230V", frequency: "50Hz" },
  RS: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  SC: { plugTypes: ["G"], voltage: "240V", frequency: "50Hz" },
  SL: { plugTypes: ["D", "G"], voltage: "230V", frequency: "50Hz" },
  SG: { plugTypes: ["G"], voltage: "230V", frequency: "50Hz" },
  SK: { plugTypes: ["C", "E"], voltage: "230V", frequency: "50Hz" },
  SI: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  SB: { plugTypes: ["G", "I"], voltage: "220V", frequency: "50Hz" },
  SO: { plugTypes: ["C"], voltage: "220V", frequency: "50Hz" },
  ZA: { plugTypes: ["C", "D", "M", "N"], voltage: "230V", frequency: "50Hz" },
  SS: { plugTypes: ["C", "D"], voltage: "230V", frequency: "50Hz" },
  ES: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  LK: { plugTypes: ["D", "M", "G"], voltage: "230V", frequency: "50Hz" },
  SD: { plugTypes: ["C", "D"], voltage: "230V", frequency: "50Hz" },
  SR: { plugTypes: ["C", "F"], voltage: "127V", frequency: "60Hz" },
  SE: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  CH: { plugTypes: ["C", "J"], voltage: "230V", frequency: "50Hz" },
  SY: { plugTypes: ["C", "E", "L"], voltage: "220V", frequency: "50Hz" },
  TW: { plugTypes: ["A", "B"], voltage: "110V", frequency: "60Hz" },
  TJ: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  TZ: { plugTypes: ["D", "G"], voltage: "230V", frequency: "50Hz" },
  TH: { plugTypes: ["A", "B", "C", "F"], voltage: "220V", frequency: "50Hz" },
  TL: { plugTypes: ["C", "E", "F", "I"], voltage: "220V", frequency: "50Hz" },
  TG: { plugTypes: ["C"], voltage: "220V", frequency: "50Hz" },
  TO: { plugTypes: ["I"], voltage: "240V", frequency: "50Hz" },
  TT: { plugTypes: ["A", "B"], voltage: "115V", frequency: "60Hz" },
  TN: { plugTypes: ["C", "E"], voltage: "230V", frequency: "50Hz" },
  TR: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  TM: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  TV: { plugTypes: ["I"], voltage: "220V", frequency: "50Hz" },
  UG: { plugTypes: ["G"], voltage: "240V", frequency: "50Hz" },
  UA: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
  AE: { plugTypes: ["C", "D", "G"], voltage: "220V", frequency: "50Hz" },
  GB: { plugTypes: ["G"], voltage: "230V", frequency: "50Hz" },
  US: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  UY: { plugTypes: ["C", "F", "I", "L"], voltage: "220V", frequency: "50Hz" },
  UZ: { plugTypes: ["C", "F"], voltage: "220V", frequency: "50Hz" },
  VU: { plugTypes: ["C", "G", "I"], voltage: "220V", frequency: "50Hz" },
  VA: { plugTypes: ["C", "F", "L"], voltage: "230V", frequency: "50Hz" },
  VE: { plugTypes: ["A", "B"], voltage: "120V", frequency: "60Hz" },
  VN: { plugTypes: ["A", "C", "G"], voltage: "220V", frequency: "50Hz" },
  YE: { plugTypes: ["A", "D", "G"], voltage: "230V", frequency: "50Hz" },
  ZM: { plugTypes: ["C", "D", "G"], voltage: "230V", frequency: "50Hz" },
  ZW: { plugTypes: ["D", "G"], voltage: "220V", frequency: "50Hz" },
  HK: { plugTypes: ["G"], voltage: "220V", frequency: "50Hz" },
  MO: { plugTypes: ["D", "G"], voltage: "220V", frequency: "50Hz" },
  PS: { plugTypes: ["C", "H"], voltage: "230V", frequency: "50Hz" },
  XK: { plugTypes: ["C", "F"], voltage: "230V", frequency: "50Hz" },
};

const defaultPower: PowerInfo = {
  plugTypes: ["Unknown"],
  voltage: "Unknown",
  frequency: "Unknown",
};

export function getPowerInfo(countryCode: string): PowerInfo {
  return powerData[countryCode.toUpperCase()] ?? defaultPower;
}
